// Norwegian / display name -> Cactus NCI lookup name (English/scientific)
export const cactusQuery = {
  'Testosteron': 'testosterone',
  'Kortisol': 'cortisol',
  'Adrenalin': 'epinephrine',
  'Epinefrin': 'epinephrine',
  'Thyroxin': 'thyroxine',
  'Progesteron': 'progesterone',
  'Aldosteron': 'aldosterone',
  'Estron': 'estrone',
  'Kortison': 'cortisone',
  'Hydrokortison': 'hydrocortisone',
  'Betametason': 'betamethasone',
  'Fludrokortison': 'fludrocortisone',
  'Medroksyprogesteron': 'medroxyprogesterone',
  'Metyltestosteron': 'methyltestosterone',
  'Androstenedion': 'androstenedione',
  'Noretyndron': 'norethindrone',
  'Etinylestradiol': 'ethinylestradiol',
  'Retinoinsyre': 'retinoic acid',
  'Acetylkolin': 'acetylcholine',
  'Noradrenalin': 'norepinephrine',
  'Vitamin C': 'ascorbic acid',
  'Vitamin A': 'retinol',
  'Vitamin D3': 'cholecalciferol',
  'Vitamin E': 'alpha-tocopherol',
  'Vitamin K1': 'phylloquinone',
  'Thiamin (B1)': 'thiamine',
  'Riboflavin (B2)': 'riboflavin',
  'Niacin (B3)': 'nicotinic acid',
  'Pyridoksin (B6)': 'pyridoxine',
  'Biotin (B7)': 'biotin',
  'Folsyre (B9)': 'folic acid',
  'Kobalamin (B12)': 'cyanocobalamin',
  'Acetylsalisylsyre': 'aspirin',
  'Amoksicillin': 'amoxicillin',
  'Morfium': 'morphine',
  'Glycin': 'glycine',
  'Alanin': 'alanine',
  'Valin': 'valine',
  'Leucin': 'leucine',
  'Isoleucin': 'isoleucine',
  'Prolin': 'proline',
  'Serin': 'serine',
  'Treonin': 'threonine',
  'Cystein': 'cysteine',
  'Metionin': 'methionine',
  'Aspartat': 'aspartic acid',
  'Glutamin': 'glutamine',
  'Lysin': 'lysine',
  'Arginin': 'arginine',
  'Histidin': 'histidine',
  'Fenylalanin': 'phenylalanine',
  'Tyrosin': 'tyrosine',
  'Tryptofan': 'tryptophan',
  'Asparagin': 'asparagine',
  'Glutamat': 'glutamic acid',
  'Histamin': 'histamine',
  'Glukose': 'glucose',
  'Fruktose': 'fructose',
  'Sukrose': 'sucrose',
  'Laktose': 'lactose',
  'Ribose': 'ribose',
  'Deoksyribose': '2-deoxyribose',
  'Maltose': 'maltose',
  'Galaktose': 'galactose',
  'Mannose': 'mannose',
  'Acetaldehyd': 'acetaldehyde',
  'Etylamin': 'ethylamine',
  'Etanol': 'ethanol',
  'Metanol': 'methanol',
  'Formaldehyd': 'formaldehyde',
  'Eddikesyre': 'acetic acid',
  'Propionsyre': 'propionic acid',
  'Smørsyre': 'butyric acid',
  'Valeriansyre': 'valeric acid',
  'Kapronsyre': 'hexanoic acid',
  'Palmitinsyre': 'palmitic acid',
  'Stearinsyre': 'stearic acid',
  'Oleinsyre': 'oleic acid',
  'Linolensyre': 'alpha-linolenic acid',
  'Linolsyre': 'linoleic acid',
  'Arakidonsyre': 'arachidonic acid',
  'Nikotin': 'nicotine',
  'Kinidin': 'quinidine',
  'Kokain': 'cocaine',
  'Atropin': 'atropine',
  'Kinin': 'quinine',
  'Kodein': 'codeine',
  'Kapsaikin': 'capsaicin',
  'Teobromin': 'theobromine',
  'Stryknin': 'strychnine',
  'Etylen': 'ethylene',
  'Acetylen': 'acetylene',
  'Benzen': 'benzene',
  'Toluen': 'toluene',
  'Fenol': 'phenol',
  'Anilin': 'aniline',
  'Benzoesyre': 'benzoic acid',
  'Aceton': 'acetone',
  'Dietyleter': 'diethyl ether',
  'Diklormetan': 'dichloromethane',
  'Kloroform': 'chloroform',
  'Etylacetat': 'ethyl acetate',
  'Amoniakk': 'ammonia',
  'Metan': 'methane',
  'Etan': 'ethane',
  'Propan': 'propane',
  'Butan': 'butane',
  'Cykloheksan': 'cyclohexane',
  'Naftalen': 'naphthalene',
  'Antracen': 'anthracene',
  'Pyridin': 'pyridine',
  'Vanillin': 'vanillin',
  'Salicylsyre': 'salicylic acid',
  'Sitronsyre': 'citric acid',
  'Melkesyre': 'lactic acid',
  'Pyruvinsyre': 'pyruvic acid',
  'Oksalsyre': 'oxalic acid',
  'Malonsyre': 'malonic acid',
  'Sukkinsyre': 'succinic acid',
  'Fumarsyre': 'fumaric acid',
  'Maleinsyre': 'maleic acid',
  'Benzaldehyd': 'benzaldehyde',
  'Asetofenon': 'acetophenone',
  'Benzonitril': 'benzonitrile',
  'Kreatin': 'creatine',
  'Taurin': 'taurine',
  'Karnitin': 'L-carnitine',
  'Koensym Q10': 'ubiquinone',
  'Alpha-liponsyre': 'alpha-lipoic acid',
  'D-Ribose': 'ribose',
  'Acetonitril': 'acetonitrile',
  'Heksan': 'hexane',
  'Heptan': 'heptane',
  'Sykloheksanon': 'cyclohexanone',
  'Trietylenamin': 'triethylamine',
  'Hydroksylamin': 'hydroxylamine',
  'Metylamin': 'methylamine',
  'Etylenoksid': 'ethylene oxide',
  'Propylenoksid': 'propylene oxide',
  'Pyrrol': 'pyrrole',
  'Pyrrolidin': 'pyrrolidine',
  'Piperidin': 'piperidine',
  'Morpholin': 'morpholine',
  'Piperazin': 'piperazine',
  'Azetidin': 'azetidine',
  'Fenylazid': 'phenyl azide',
  'Boronsyre': 'boric acid',
  'Izocyanat': 'methyl isocyanate',
  'Tiocyanat': 'methyl thiocyanate',
  'Distikstoffoksid': 'nitrous oxide',
  'Dioksygen': 'oxygen',
  'Triiodotyronin': 'triiodothyronine',
  'DHEA': 'dehydroepiandrosterone',
  'Prostaglandin E2': 'prostaglandin E2',
  'Prostaglandin F2α': 'prostaglandin F2',
  'Prostaglandin I2': 'prostaglandin I2',
  'Tromboxan B2': 'thromboxane B2',
  '17-Hydroksyprogesteron': '17-hydroxyprogesterone',
  'Drospirenon': 'drospirenone',
  'Cyproteronacetat': 'cyproterone acetate',
  'Mesterolon': 'mesterolone',
  'Vitamin K1': 'phylloquinone',
  'Folsyre (B9)': 'folic acid',
  'Kobalamin (B12)': 'cyanocobalamin',
  'Glukosamin': 'glucosamine',
  'Cellulose': 'cellulose',
  'Eugenol': 'eugenol',
  'Resveratrol': 'resveratrol',
  'Kurkumin': 'curcumin',
  'Quercetin': 'quercetin',
  'Epigallocatechingallat': 'epigallocatechin gallate',
  'Omega-3 DHA': 'docosahexaenoic acid',
  'L-Glutathion': 'glutathione',
  'PQQ': 'pyrroloquinoline quinone',
  '4-Metylpyridin': '4-methylpyridine',
  'Tetrahydrofuran': 'tetrahydrofuran',
  'Urea': 'urea',
  'Dihydrotestosteron': 'dihydrotestosterone',
  'Prednisolon': 'prednisolone',
  'Dexametason': 'dexamethasone',
  'Spironolakton': 'spironolactone',
  'Omeprazol': 'omeprazole',
  'Sertralin': 'sertraline',
  'Fruktose-6-fosfat': 'fructose-6-phosphate',
  'Metanol': 'methanol',
  'Amoniakk': 'ammonia',
  'Metan': 'methane',
  'Etan': 'ethane',
  'Tiofen': 'thiophene',
  'Natriumoksalat': 'sodium oxalate',
  'Etyllaktat': 'ethyl lactate',
  'Trietylfosfat': 'triethyl phosphate',
  'Dimetylsulfat': 'dimethyl sulfate',
  'Etylnitrat': 'ethyl nitrate',
  'Dietylkarbonat': 'diethyl carbonate',
  'Hydroksylamin': 'hydroxylamine',
  'Metylamin': 'methylamine',
  'Metylazid': 'methyl azide',
  'H2O2': 'hydrogen peroxide',
  'Dioksygen': 'oxygen',
  'NO': 'nitric oxide',
  'CO': 'carbon monoxide',
  'H2S': 'hydrogen sulfide',
  'BH3': 'borane',
  'NH3': 'ammonia',
  'PH3': 'phosphine',
  'SiH4': 'silane',
  'SO2': 'sulfur dioxide',
  'CS2': 'carbon disulfide',
  'CO2': 'carbon dioxide',
  'Distikstoffoksid': 'nitrous oxide',
};
